# Generated by Django 2.0.10 on 2019-03-18 20:44

import apps.base.utils
import apps.images.models
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.CharField(default=apps.base.utils.custom_uuid, editable=False, max_length=11, primary_key=True, serialize=False)),
                ('original_image', models.ImageField(blank=True, null=True, upload_to=apps.images.models.image_path)),
                ('preview_image', models.ImageField(blank=True, editable=False, null=True, upload_to=apps.images.models.image_path)),
            ],
            options={
                'db_table': 'images',
            },
        ),
    ]
